### ISSUE TITLE
Add a close button to the help/instructions windows

### ISSUE THREAD

**Issue by FrostyNarwhal** [UCSB-CS56-Projects/cs56-misc-translate-to-secret-languages#28] opened 2016-03-10 23:14 UTC
Add buttons on the help/instruction pop up windows to close them instead of using the default x in the corner of the window. Make it look more like the rest of the interface.

~50 points

**Comment by ashedden** [comment] 2016-03-11 21:32
W16 ok!

**Comment by jmangel** [comment] 2016-09-26 19:56
Duplicate of #35

**Closed by jmangel** 2016-09-26 19:56 UTC
